;; -*- mode: emacs-lisp; lexical-binding:t; coding: utf-8-emacs; -*-
;; -------------------------------------------------------------------------
;; Tabspaces Session File for Emacs
;; -------------------------------------------------------------------------
;; Created Mon Dec  8 17:56:27 2025

;; Project to tab name mapping:
(setq tabspaces-project-tab-map '(("~/projects/embarcas/" . "embarcas") ("~/projects/embarcas/" . "embarcas") ("~/projects/embarcas/" . "embarcas")))

;; Tab and buffers:
(setq tabspaces--session-list '((("/home/embarcas/projects/embarcas/Makefile" "/home/embarcas/projects/embarcas/Makefile.bkp" "/home/embarcas/projects/embarcas/CMakeLists.txt" "/home/embarcas/projects/embarcas/src/main.c" "/home/embarcas/projects/embarcas/src/learning/led.c" "/home/embarcas/projects/embarcas/include/learning/led.h" "/home/embarcas/ayedero/.emacs" "/home/embarcas/projects/embarcas/include/avr/io_attiny85.h" "/home/embarcas/projects/embarcas/include/avr/io_atmega328p.h" "/home/embarcas/projects/embarcas/include/led/" "/home/embarcas/projects/embarcas/include/led/led.h" "/home/embarcas/projects/embarcas/src/led/led.c" "/home/embarcas/projects/embarcas/include/learning/button.h" "/home/embarcas/projects/embarcas/include/avr/iotnx5.h" "/home/embarcas/projects/embarcas/include/io/io.h" "/home/embarcas/projects/embarcas/src/learning/button.c") "embarcas" (((min-height . 4) (min-width . 20) (min-height-ignore . 3) (min-width-ignore . 8) (min-height-safe . 1) (min-width-safe . 4) (min-pixel-height . 100) (min-pixel-width . 220) (min-pixel-height-ignore . 75) (min-pixel-width-ignore . 88) (min-pixel-height-safe . 25) (min-pixel-width-safe . 44)) hc (pixel-width . 1872) (pixel-height . 945) (total-width . 170) (total-height . 38) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (leaf (pixel-width . 936) (pixel-height . 945) (total-width . 85) (total-height . 38) (normal-height . 1.0) (normal-width . 0.5) (buffer "src" (selected) (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 330) (start . 1)) (prev-buffers ("embarcas" 1 1094) ("Makefile.bkp" 322 813) ("main.c" 1 437))) (leaf (last . t) (pixel-width . 936) (pixel-height . 945) (total-width . 85) (total-height . 38) (normal-height . 1.0) (normal-width . 0.5) (buffer "Makefile" (selected . t) (hscroll . 0) (fringes 8 8 nil nil) (margins nil) (scroll-bars nil 0 t nil 0 t nil) (vscroll . 0) (dedicated) (point . 260) (start . 1)) (prev-buffers ("embarcas" 1 967) ("CMakeLists.txt" 1 149) ("main.c" 1 437) ("iotnx5.h" 1 1) ("led.c<learning>" 1 44) ("led.h<learning>" 1 15) ("led.h<led>" 1 1)))))))